apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fonj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-fonj@sha256:b50c75f5306748fe748e318ebbf70548a4fe7edde29cd596ed83a5500d9434ff
        name: my-nodejs
        resources: {}
status: {}
